- google-redis.yml
The examples tests were failing as they created the GCP default version
of Redis which is now REDIS_6_X and this was not matching any of the
known versions.
[#180164570](https://www.pivotaltracker.com/story/show/180164570)
> fix: update versions of Redis

- google-dataproc.yml
- terraform/bind-dataproc.tf
The update to terraform-provider-google@v4.0.0 broke Dataproc because
the project parameter is now required when creating a
`google_project_iam_member`.
https://github.com/cloudfoundry-incubator/csb-brokerpak-gcp/commit/555668afebd7cde6b9b535cdc23c42604c56598c
[#180192255](https://www.pivotaltracker.com/story/show/180192255)
> chore: fix dataproc since provider update

- acceptance-tests/helpers/brokers/env.go
- docs/draft-release-notes.md
- google-postgresql.yml
- scripts/push-broker.sh
BREAKING CHANGE:
In order to facilitate configuration of plans, the default plans for
PostgreSQL have been removed. Plans should be specified via the
environment variable GSB_SERVICE_CSB_GOOGLE_POSTGRES_PLANS. This allows
the default plans to be completely removed, wheras previously it was
only possible to add additional plans.
[#181059527](https://www.pivotaltracker.com/story/show/181059527)
> feat!: PostgreSQL service should have no default plans

- acceptance-tests/helpers/brokers/create.go
- acceptance-tests/helpers/brokers/env.go
- acceptance-tests/helpers/brokers/update.go
- acceptance-tests/upgrade/update_and_upgrade_postgresql_test.go
- acceptance-tests/upgrade/update_and_upgrade_redis_test.go
- acceptance-tests/upgrade/update_and_upgrade_storage_test.go
- Change helpers to cater for env variables defining the plans
- Comment out deletion of postgresql schema that fails (raising a bug instead)
[#180082688](https://www.pivotaltracker.com/story/show/180082688)
> test: upgrade tests support env plans

- docs/configuration.md
- docs/draft-release-notes.md
Adds docs for the new `beta` feature flag work done on CSB.
[#181267511](https://www.pivotaltracker.com/story/show/181267511)
> docs: beta services now disabled by default by csb

- google-mysql.yml
- google-postgresql.yml
- integration-tests/mysql_test.go
- integration-tests/postgres_test.go
- integration-tests/results/mysql-result.json
- terraform/cloudsql/mysql/bind/outputs.tf
- terraform/cloudsql/mysql/bind/provider.tf
- terraform/cloudsql/mysql/bind/variables.tf
- terraform/cloudsql/mysql/provision/outputs.tf
- terraform/cloudsql/mysql/provision/variables.tf
- terraform/cloudsql/postgresql/bind/outputs.tf
- terraform/cloudsql/postgresql/bind/provider.tf
- terraform/cloudsql/postgresql/bind/variables.tf
- terraform/cloudsql/postgresql/provision/outputs.tf
- terraform/cloudsql/postgresql/provision/variables.tf
Since the tf definitions are split the ports dont need to be passed from provision step anymore
> chore: Set mysql and postgres ports as local vars

- acceptance-tests/helpers/brokers/create.go
- acceptance-tests/helpers/brokers/env.go
- acceptance-tests/helpers/brokers/update.go
- acceptance-tests/upgrade/update_and_upgrade_postgresql_test.go
- acceptance-tests/upgrade/update_and_upgrade_redis_test.go
- acceptance-tests/upgrade/update_and_upgrade_storage_test.go
The upgrade tests test the upgrade from one version (the starting point)
to the very latest. Since we released this brokerpak recently, the
starting point has now moved and includes the change to make the
PostgreSQL plan an environment variable. As such we need to adjust the
tests to set this variable for the starting point as well as the end
point.
> test: fix up upgrade tests for new starting point

- docs/draft-release-notes.md
- google-postgresql.yml
- integration-tests/postgres_test.go
- terraform/cloudsql/postgresql/provision/main.tf
- terraform/cloudsql/postgresql/provision/variables.tf
New properties: backups_retain_number, backups_location,
backups_start_time and backups_point_in_time_log_retain_days
[#181060141](https://www.pivotaltracker.com/story/show/181060141)
> feat: PostgreSQL backup can be configured

- docs/draft-release-notes.md
- terraform/cloudsql/postgresql/provision/main.tf
Some older PostgreSQL clients don't support this setting, so we might
need to make it optional in future. But the improved security make it
worthwhile.
[#181742593](https://www.pivotaltracker.com/story/show/181742593)
> feat: PostgreSQL scam password encryption

- acceptance-tests/upgrade/update_and_upgrade_postgresql_test.go
This reverts commit f410b1d51c1cdadabf5fd7c68eb6a969f1491a34.
We can do this because we now test with a later "old version" in the
upgrade tests, so this behaviour will now work.
[#181701604](https://www.pivotaltracker.com/story/show/181701604)
> test: revert "unbind postgres before updating broker (#267)"

- acceptance-tests/apps/dataprocapp/app/run_job.go
New code should not use ioutil as its on the path to deprecation
> chore: don't use ioutil package

- acceptance-tests/apps/postgresqlapp/internal/app/app.go
- acceptance-tests/apps/postgresqlapp/internal/credentials/credentials.go
- acceptance-tests/apps/postgresqlapp/main.go
This restores functionality from commit
https://github.com/cloudfoundry/csb-brokerpak-gcp/commit/f5cff4b75aba3f14d4550574222fa963b82c65e7 which had to be reverted. The
TLS functionality is not used yet. The plan is to enable that in a
future commit.
> test: PostgreSQL app should be able to use TLS 

- docs/draft-release-notes.md
- google-postgresql.yml
- integration-tests/postgres_test.go
- manifest.yml
- terraform/cloudsql/postgresql/bind/main.tf
- terraform/cloudsql/postgresql/bind/outputs.tf
- terraform/cloudsql/postgresql/bind/provider.tf
- terraform/cloudsql/postgresql/bind/variables.tf
- terraform/cloudsql/postgresql/bind/versions.tf
- terraform/cloudsql/postgresql/provision/main.tf
- terraform/cloudsql/postgresql/provision/outputs.tf
- terraform/cloudsql/postgresql/provision/provider.tf
- terraform/cloudsql/postgresql/provision/versions.tf
This restores the functionality from f5cff4b which was previously reverted.
> feat(PostgreSQL): connections should require TLS

- providers/terraform-provider-csbpg/Makefile
The CI for the "examples" tests runs in a container without Go. This
change should get that working again.
[#181898458](https://www.pivotaltracker.com/story/show/181898458)
> build: allow provider to build in Go-less environment

- Makefile
- acceptance-tests/helpers/brokers/env.go
- docs/configuration.md
- docs/draft-release-notes.md
- google-postgresql.yml
- scripts/push-broker.sh
Upgrading from previous (beta) versions will not be possible due to the
number of changes. So the service offering GUID and plan GUIDs have been
changed to avoid accidental upgrades. Any attempt to upgrade will result
in a CloudFoundry error.
[#182060896](https://www.pivotaltracker.com/story/show/182060896)
> feat!: change PostgreSQL GUIDs to prevent upgrade

- Makefile
- providers/terraform-provider-csbpg/Makefile
- new check only prints when there is an error
- new check does not allow substring matches
[#181960182](https://www.pivotaltracker.com/story/show/181960182)
> chore: improve Go version check

- docs/draft-release-notes.md
- terraform/cloudsql/postgresql/provision/main.tf
When the "prevent_destroy" property is true, Terraform will not
allow the resource to be deleted. This provides extra protection
during a service update as sometimes changing properties (e.g
the database name) can cause the database to be deleted and re-created.
We think we have blocked changing all the destructive properties,
but this adds an extra layer of protection against data loss in
case of error.
[#181445529](https://www.pivotaltracker.com/story/show/181445529)
> fix: add lifecycle.prevent_destroy to PostgreSQL

- Makefile
- integration-tests/mysql_test.go
- integration-tests/postgres_test.go
- integration-tests/redis_test.go
- a recent change made to the broker core results in a check of
the terraform state before performing an update. This change ensures
that the state gets initialised before the provision step.
[#182208889](https://www.pivotaltracker.com/story/show/182208889)
> test: fix test setup

- acceptance-tests/helpers/services/create.go
Tests that don't use the default broker should not fail when the default
broker is not deployed
[#182413672](https://www.pivotaltracker.com/story/show/182413672)
> test: allow runs without default broker

- acceptance-tests/errormessages_test.go
This is due to a fix in the CSB which removes duplicate spaces
https://github.com/cloudfoundry/cloud-service-broker/commit/36c31b9b21e4e72a8b67ce78e24659558fdb5acf
> test: update spacing in error message to match current message

- docs/draft-release-notes.md
- google-bigquery.yml
- google-storage.yml
- integration-tests/bigquery_test.go
- integration-tests/storage_test.go
It can result in the recreation of the service instance and lost data.
[#182548851](https://www.pivotaltracker.com/story/show/182548851)
> fix: region cannot be updated

- acceptance-tests/upgrade/update_and_upgrade_dataproc_test.go
- acceptance-tests/upgrade/update_and_upgrade_redis_test.go
- acceptance-tests/upgrade/update_and_upgrade_spanner_test.go
- docs/draft-release-notes.md
- google-dataproc.yml
- google-redis.yml
- integration-tests/redis_test.go
Redis instance_id and dataproc name default values were relying on timestamp. That causes every subsequent operation (update/upgrade) to regenerate the variable and that triggers tf to destroy the original instance.
[#182570764](https://www.pivotaltracker.com/story/show/182570764)
Co-Authored-By: Marcela Campo <20945140+pivotal-marcela-campo@users.noreply.github.com>
> fix: Change the default name to not rely on timestamp

- acceptance-tests/helpers/apps/app.go
- acceptance-tests/helpers/apps/push.go
- acceptance-tests/helpers/apps/setenv.go
- acceptance-tests/helpers/brokers/create.go
- acceptance-tests/helpers/brokers/manifest.go
- go.mod
- scripts/push-broker.sh
By skipping repeated "cf set-env" commands and instead putting the
environment variables in the manifest, this change results in faster
deployment of the broker
[#182771270](https://www.pivotaltracker.com/story/show/182771270)
> chore: push the broker faster

- manifest.yml
It seems that the script that updates Terraform providers expects fields
in a certain order: name, version, source. If we keep things in that
order then it will work correctly. We plan to rework the provider update
in https://www.pivotaltracker.com/story/show/181478730, so it's not
worth improving the current script to be more flexible.
[#182961253](https://www.pivotaltracker.com/story/show/182961253)
> build(deps): fix previous bump terraform provider

- acceptance-tests/helpers/apps/prebuild.go
The Spanner acceptance test tries to build a Spanner app. For some reason this build is comparatively slow for a Go app. It often takes 50 seconds in CI, and took 90 seconds on my workstation. The timeout is 60 seconds, hence 8 failures in the past week when it went over the timeout. I've therefore increased the timeout to 5 minutes, so when it times out we know that something remarkable has happened, rather that just being a little slower than usual.
> test: fix flake in Spanner test

- acceptance-tests/apps/mysqlapp/internal/credentials/credentials.go
- google-mysql.yml
- terraform-tests/mysql_test.go
- terraform/cloudsql/mysql/bind/main.tf
- terraform/cloudsql/mysql/bind/outputs.tf
- terraform/cloudsql/mysql/bind/variables.tf
- terraform/cloudsql/mysql/provision/main.tf
- terraform/cloudsql/mysql/provision/outputs.tf
- terraform/cloudsql/postgresql/provision/variables.tf
Reverts cloudfoundry/csb-brokerpak-gcp#592
Acceptance tests do not pass correctly: 
```
failed to create test table: x509: cannot validate certificate for 10.160.104.9 because it doesn't contain any IP SANs
```
> chore: revert "feat: [mysql] enable TLS"

- integration-tests/integration_tests_suite_test.go
- integration-tests/mysql_test.go
- integration-tests/postgres_test.go
- integration-tests/redis_test.go
The integration tests contained a lot of:
```
Expect(foo).ToNot(BeNil())
```
which for a string value can never fail. These tests have been improved to match against expected data.
> test: improve matching in integration tests

- acceptance-tests/mysql_test.go
- docs/installation.md
- google-mysql.yml
- integration-tests/mysql_test.go
It was referred to as "Mysql" in places, which does not match the MySQL branding.
> fix: capitalization of MySQL

- acceptance-tests/apps/mysqlapp/internal/credentials/credentials.go
[#184053043](https://www.pivotaltracker.com/story/show/184053043)
> chore: TLS is disabled when using the old bind format

- terraform-tests/storage_test.go
- terraform/storage/provision/main.tf
We need to use the dynamic block when defining the autoclass block to avoid setting the property when updating the service and not recreating the bucket.
[#184267802](https://www.pivotaltracker.com/story/show/184267802)
> chore: avoid recreation bucket using the dynamic block

- google-storage.yml
- integration-tests/storage_test.go
Added the same regular expression used in the Terraform provider, in this way we will get a faster feedback.
The TF provider forces the recreation of the bucket when changing the name. Added `prohibit_update` to avoid it.
[#184053558](https://www.pivotaltracker.com/story/show/184053558)
> chore: improve constraints in bucket name

- acceptance-tests/cloudsql_mysql_migration_test.go
- acceptance-tests/helpers/brokers/env.go
- acceptance-tests/postgresql_test.go
- acceptance-tests/withoutcredhub_test.go
When pushing a broker for a test, you now have to explicitly choose whether you want the env for the latest released, or for latest development.
We were getting errors for duplicate plan GUIDs when service GUIDs changed:
```
Plan ids must be unique. Unable to register plan with id 'eec62c9b-b25e-4e65-bad5-6b74d90274bf' (plan name 'default', service name 'csb-google-mysql') because it uses the same id as an existing plan (plan name 'default', service name 'csb-google-mysql', broker name 'csb-storage-alder-slicer')
```
> test: separate out released and development env vars

- acceptance-tests/cloudsql_mysql_migration_test.go
- acceptance-tests/cloudsql_pg_migration_test.go
- acceptance-tests/dataproc_test.go
- acceptance-tests/helpers/apps/payload.go
- acceptance-tests/postgresql_test.go
- acceptance-tests/redis_test.go
- acceptance-tests/spanner_test.go
- acceptance-tests/storage_migration_test.go
- acceptance-tests/storage_test.go
- acceptance-tests/upgrade/update_and_upgrade_dataproc_test.go
- acceptance-tests/upgrade/update_and_upgrade_mysql_test.go
- acceptance-tests/upgrade/update_and_upgrade_postgresql_test.go
- acceptance-tests/upgrade/update_and_upgrade_redis_test.go
- acceptance-tests/upgrade/update_and_upgrade_spanner_test.go
- acceptance-tests/upgrade/update_and_upgrade_storage_test.go
- acceptance-tests/withoutcredhub_test.go
- explicitly casts payloads before comparison to avoid type mismatch
- updates the plan used for "without credhub" test to one that exists
> test: fixes for previous improvements

- acceptance-tests/apps/postgresqlapp/internal/app/create_schema.go
[#185431677]
Although granting permissions to a specific table might be a perfectly valid operation for an app to do, having it in our tests might be hiding some permissions issues related to: dataOwnerUser, binding creation, etc.
> fix: [Postgres] remove explicit grant from acceptance_tests

- acceptance-tests/postgresql_test.go
[#185431677]
Binding operations of GCP can fail if a previous binding has created objects in the PUBLIC schema.
Several factors converged making it unnoticeable to our CI:
- Apps GRANTed permission to the table to PUBLIC
- Tests created all bindings before creating any db object
This commit exposes the bug by delaying the creation of the second binding until the first app creates some tables.
> fix: [Postgres] expose bug so we can debug it and fix it

- Makefile
[#185955999](https://www.pivotaltracker.com/story/show/185955999)
shell instruction will mask any error happening in GET_CSB command such as errors resolving dependencies due to some network issue
> fix: [CI] build-broker-brokerpak masking errors

- acceptance-tests/postgresql_test.go
When we started GAing services our approach was to test GAed services with the ENABLE_BETA_SERVICE_OFFERINGS flag to false. In this way we could also test that the GAed service would be always available. We haven't replicated this kind of approach for other services so this now is not consistent with the rest of the tests. It would be better to just have a dedicated test for the catalog to double check this behavior than to slow down our tests and consume extra resources by pushing yet another broker
[#186011659](https://www.pivotaltracker.com/story/show/186011659)
> chore: avoid pushing the broker in acceptance tests unnecessarily

- .github/dependabot.yml
This will result in more PRs, but it will bring us close to always being ready to release.
> chore: run Dependabot daily

- .github/dependabot.yml
We see lots of Dependabot PR conflicts which are easy to resolve, but if we configure Dependabot to run at different times for different modules, then hopefully we will see fewer conflicts in the first place.
> chore: spread out Dependabot updates

- manifest.yml
In order to reduce the size of the brokerpak, obsolete Terraform providers have been removed. As a result, to get to this version through upgrading, you must upgrade to v1.3 first and upgrade all service instances to v1.3. This can be done via "cf upgrade-service", or for bulk upgrades consider the plugin: https://github.com/cloudfoundry/upgrade-all-services-cli-plugin You can then upgrade to this version, and again upgrade all the service instances.
[#186588913](https://www.pivotaltracker.com/story/show/186588913)
> feat: restrict upgrade to v1.3 only

- Makefile
- README.md
The same benefits can be achieved by simply launching an interactive docker session inside a supported image and running commands from there. This approach has some additional benefits
- Easier to maintain
- Debloats Makefile
- Less hidden magic
- Same code for local and containerised execution
> chore: remove run-in-docker logic from Makefile

- .github/workflows/codeql.yml
Related PRs:
- https://github.com/argentumcode/systemd-failure-pagerduty/pull/8/files
> chore: make codeql action use golang specified in go.mod (#1516)

- go.mod
Related PRs:
- https://github.com/cloudfoundry/csb-brokerpak-gcp/pull/1044
> chore: specify go 1.22.0 in go.mod

- scripts/push-broker.sh
Previously we would always try and create the broker, and if that failed (for any reason) then attempt to update it. This resulted in output that sometimes confused users.
> chore: use --update-if-exists when creating broker

- terraform/bigquery/bind/variables.tf
- terraform/bigquery/provision/variables.tf
- terraform/dataproc/provision/variables.tf
- terraform/redis/provision/variables.tf
- terraform/spanner/provision/variables.tf
- terraform/stackdriver/bind/variables.tf
- terraform/storage/bind/variables.tf
- terraform/storage/provision/variables.tf
By annotating terraform variables that contain sensitive information, we ensure that they are not printed out in error messages.
Note that we have not chosen to annotate IDs (e.g. project ID) as sensitive, but only credentials. This is because printing out an ID in an error message can be very helpful.
[#183474488](https://www.pivotaltracker.com/story/show/183474488)
> chore: annotate sensitive terraform varaibles

- .github/labeler.yml
- .github/release.yml
- .github/workflows/labeler.yml
Our Concourse github releaser might not be able to do this yet as it is a bit old but we can try updating to latest.
> chore: Experiment with adding labels to each RP through this action. These labels can later be used for better release notes.

- acceptance-tests/upgrade/update_and_upgrade_spanner_test.go
The Spanner upgrade test failed when the Google Terraform provider was changed from v4 to v5. The simple workaround is to run the upgrade again and it will succeed. The test has been updated to perform this workaround.
[#187392169](https://www.pivotaltracker.com/story/show/187392169)
> test: work around spanner upgrade issue

- acceptance-tests/apps/postgresqlapp/go.mod
- acceptance-tests/apps/postgresqlapp/go.sum
- acceptance-tests/apps/postgresqlapp/internal/app/app.go
- acceptance-tests/apps/postgresqlapp/internal/app/get.go
- acceptance-tests/apps/postgresqlapp/internal/app/set.go
Go 1.22 has an improved HTTP router that means we don't need the Chi router any more.
[#187470327](https://www.pivotaltracker.com/story/show/187470327)
> test: remove Chi dependency from test app

- acceptance-tests/apps/postgresqlapp/internal/app/app.go
Fixes error:
```
panic: pattern "GET /{schema}/{key}" (registered at /tmp/build/5af53159/brokerpak/acceptance-tests/apps/postgresqlapp/internal/app/app.go:34) conflicts with pattern "HEAD /" (registered at /tmp/build/5af53159/brokerpak/acceptance-tests/apps/postgresqlapp/internal/app/app.go:27):
GET /{schema}/{key} matches more methods than HEAD /, but has a more specific path pattern
```
[#187470327](https://www.pivotaltracker.com/story/show/187470327)
> test: http method correction for PostgreSQL app

- acceptance-tests/apps/pubsubapp/internal/app/publish.go
- acceptance-tests/apps/pubsubapp/internal/app/receive.go
- publish.go: The error from `res.Get(ctx)` is not properly handled. It's printed to the ResponseWriter, but this is done inside a goroutine, which may run after the HTTP response has already been sent, leading to a potential panic or undefined behavior.
- receive.go:  the order of operations when handling the HTTP response is incorrect.
[#187726190](https://www.pivotaltracker.com/story/show/#187726190)
> fix: potential panic

- terraform/cloudsql/mysql/provision/data.tf
- terraform/cloudsql/postgresql/provision/data.tf
- terraform/redis/provision/data.tf
When `authorized_network_id` we do not need to check for the existence of `var.authorized_network`
[#187737556](https://www.pivotaltracker.com/story/show/183975388)
> fix: Should check for authorised network only when it being used

- google-pubsub.yml
[#187726204](https://www.pivotaltracker.com/story/show/187726204)
> fix: default value for subscription_retry_policy_maximum_backoff

- .github/dependabot.yml
These changes are to optimise the use of the CI. Every full run through the pipeline requires several AWS environments and several hours of tests.
> chore: Test dependencies are updated only once a week

- google-bigquery.yml
- google-dataproc.yml
- google-spanner.yml
- terraform/bigquery/bind/provider.tf
- terraform/dataproc/bind/provider.tf
- terraform/spanner/bind/provider.tf
it seems that implicit provider definitions require the GOOGLE_PROJECT und GOOGLE_CREDENTIALS ENV vars to work.
the tile based on kiln does not set env vars for the csb app anymore, it writes a "full" config before it pushes the app. These services currently fail when trying to create a bind because some fields on the required resources are `implicitly` sourced from the provider by open tofu.
[#187498188]
> chore: add provider definitions to bindings

- terraform-tests/storage_test.go
we switched the "internal" string use for dual regions like `us` to
always be lowercase in our code. But the API may still return `US`.
this updates the test to not expect a case sensitive match since both
options are correct.
> chore: update test to access case insensitive matches

- google-storage.yml
brokerpak tests currently fail with:
```
2024/06/26 10:49:28 (id=001): PUT http://5933ba03-bcae-4948-9255-c10fc6d95f2b:395053d5-a754-4029-a7b3-9e539c9418af@localhost:35627/v2/service_instances/2f9df846-3589-404b-bf7d-428c4bb18775?accepts_incomplete=true -> 500, "{\"description\":\"plan defined properties cannot be changed: region\"}\n"
2024/06/26 10:49:28 (id=001): Failed to provision csb-google-storage-bucket: unexpected response code 500
2024/06/26 10:49:28 (id=001): Cleaning up the environment
2024/06/26 10:49:28 (id=001): Unbinding csb-google-storage-bucket/gcp-bucket-multi-region (id: 20c6f1f8-9b65-43dd-9014-9b05fa4df417)
2024/06/26 10:49:28 (id=000): PUT http://5933ba03-bcae-4948-9255-c10fc6d95f2b:395053d5-a754-4029-a7b3-9e539c9418af@localhost:35627/v2/service_instances/ddbf8f93-c36f …
```
> chore: tests broken since 2c574da4b6f4b0c72001c5131e84c3d3ce6ae460

- terraform/bigquery/bind/versions.tf
- terraform/bigquery/provision/versions.tf
- terraform/cloudsql/mysql/bind/versions.tf
- terraform/cloudsql/mysql/provision/versions.tf
- terraform/cloudsql/postgresql/bind/versions.tf
- terraform/cloudsql/postgresql/provision/versions.tf
- terraform/dataproc/bind/versions.tf
- terraform/dataproc/provision/versions.tf
- terraform/redis/provision/versions.tf
- terraform/spanner/bind/versions.tf
- terraform/spanner/provision/versions.tf
- terraform/stackdriver/bind/versions.tf
- terraform/storage/bind/versions.tf
- terraform/storage/provision/versions.tf
The operator is a convenient shorthand that allows the rightmost component of a version to increment. The fix also corrects the Terraform test by downloading the current provider version.
> feat: use operator ~> as version constraint

- .github/dependabot.yml
The stackdriver test app has been removed in a previous commit, and this change stops Dependabot from trying to keep it updated
> chore: update Dependabot config for obsolete test app

- terraform/cloudsql/mysql/provision/main.tf
PostgreSQL checks client certificates. MySQL should do the same. Has additional benefit that in the GCP console it is reported that only TLS connections are accepted. (Currently only TLS connections are accepted because this is added as a setting to every user, but as it's not shown in the console, it can look like the database would accept insecure connections)
> feat: MySQL should check client certificate

- acceptance-tests/helpers/services/delete.go
- acceptance-tests/upgrade/update_and_upgrade_mysql_test.go
- acceptance-tests/upgrade/update_and_upgrade_postgresql_test.go
- acceptance-tests/upgrade/update_and_upgrade_storage_test.go
- acceptance-tests/withoutcredhub_test.go
We can only have 5 instances of our test broker running. Tests that use the test broker can see 'failed to allocate' errors. This is because in the case of a failed creation of a service in our tests will fail to clean up the test broker, causing other test runs to fail.
> chore: Fixes broker 'failed to allocate errors'

- acceptance-tests/helpers/services/delete.go
- acceptance-tests/upgrade/update_and_upgrade_mysql_test.go
- acceptance-tests/upgrade/update_and_upgrade_postgresql_test.go
- acceptance-tests/upgrade/update_and_upgrade_storage_test.go
- acceptance-tests/withoutcredhub_test.go
We can only have 5 instances of our test broker running. Tests that use the test broker can see 'failed to allocate' errors. This is because in the case of a failed creation of a service in our tests will fail to clean up the test broker, causing other test runs to fail.
> chore: Fixes broker 'failed to allocate' test errors

- acceptance-tests/helpers/apps/http.go
- acceptance-tests/mysql_test.go
- acceptance-tests/postgresql_test.go
- acceptance-tests/storage_test.go
- acceptance-tests/upgrade/update_and_upgrade_mysql_test.go
- acceptance-tests/upgrade/update_and_upgrade_postgresql_test.go
Changes to integration tests to satisfy Go 1.24 new requirement for format strings to be constants.
> chore: fix failures due to Go 1.24

- manifest.yml
There is a behaviour change in OpenTofu v1.10, and while we work out how to deal with it, we will switch back to v1.9.1
https://github.com/opentofu/opentofu/issues/2977
> chore: revert to OpenTofu v1.9
