- docs/gcp-installation.md
[#177324823](https://www.pivotaltracker.com/story/show/177324823)
> docs: additional APIs that need to be enabled

- google-bigquery.yml
- google-dataproc.yml
- google-mysql.yml
- google-postgresql.yml
- google-redis.yml
- google-spanner.yml
- google-stackdriver-trace.yml
- google-storage.yml
[#181062391](https://www.pivotaltracker.com/story/show/181062391)
> Add "Beta" tag in tags and description for all services

- Makefile
[#181059527](https://www.pivotaltracker.com/story/show/181059527)
* ~~[ ] Have you added Draft Release Notes in `docs/draft-release-notes.md`?~~ N/A
> test: examples tests need to defined PostgreSQL plans

- docs/draft-release-notes.md
- google-postgresql.yml
- integration-tests/postgres_test.go
> feat: prevent instance parameter updates for postgres

- integration-tests/postgres_test.go
> test: MySQL bind test asserts for output override

- manifest.yml
[#180913401]
~~* [ ] Have you added Draft Release Notes in `docs/draft-release-notes.md`?~~
> feat: replacing postgres provider for upgrading SIs

- docs/draft-release-notes.md
- google-postgresql.yml
- integration-tests/postgres_test.go
> feat: changed postgres default

- google-mysql.yml
- google-postgresql.yml
- integration-tests/mysql_test.go
- integration-tests/postgres_test.go
- integration-tests/results/mysql-result.json
- terraform/cloudsql/provision/outputs.tf
- terraform/cloudsql/provision/variables.tf
[#181059661]
~~* [ ] Have you added Draft Release Notes in `docs/draft-release-notes.md`?~~
> fix: configure provider specific ports from the brokerpak files

- Makefile
- integration-tests/postgres_test.go
- scripts/push-broker.sh
[#181059661](https://www.pivotaltracker.com/story/show/181059661)
> test: fix posgresql version in table test entry

- acceptance-tests/upgrade/update_and_upgrade_postgresql_test.go
[#181525059](https://www.pivotaltracker.com/story/show/181525059)
Co-authored-by: Felisia Martini <fmartini@pivotal.io>
* [] Have you added Draft Release Notes in `docs/draft-release-notes.md`? N/A
> test(upgrade): change postgres test to use schema

- acceptance-tests/upgrade/update_and_upgrade_postgresql_test.go
[#181525059](https://www.pivotaltracker.com/story/show/181525059)
Co-authored-by: Marcela Campo <mcampo@pivotal.io>
> test(upgrade): unbind postgres before updating broker

- google-mysql.yml
- google-postgresql.yml
- integration-tests/mysql_test.go
- integration-tests/postgres_test.go
- integration-tests/results/mysql-result.json
- terraform/cloudsql/mysql/bind/outputs.tf
- terraform/cloudsql/mysql/bind/provider.tf
- terraform/cloudsql/mysql/bind/variables.tf
- terraform/cloudsql/mysql/provision/outputs.tf
- terraform/cloudsql/mysql/provision/variables.tf
- terraform/cloudsql/postgresql/bind/outputs.tf
- terraform/cloudsql/postgresql/bind/provider.tf
- terraform/cloudsql/postgresql/bind/variables.tf
- terraform/cloudsql/postgresql/provision/outputs.tf
- terraform/cloudsql/postgresql/provision/variables.tf
> chore: Set mysql and postgres ports as local vars 

- acceptance-tests/README.md
- acceptance-tests/helpers/brokers/create.go
[#181108660](https://www.pivotaltracker.com/story/show/181108660)
> test: Fix broker source dir after test folders moved

- acceptance-tests/apps/dataprocapp/app/run_job.go
- acceptance-tests/apps/postgresqlapp/internal/app/app.go
- acceptance-tests/apps/postgresqlapp/internal/credentials/credentials.go
- docs/draft-release-notes.md
- google-postgresql.yml
- integration-tests/postgres_test.go
- manifest.yml
- terraform/cloudsql/postgresql/bind/main.tf
- terraform/cloudsql/postgresql/bind/outputs.tf
- terraform/cloudsql/postgresql/bind/provider.tf
- terraform/cloudsql/postgresql/bind/variables.tf
- terraform/cloudsql/postgresql/bind/versions.tf
- terraform/cloudsql/postgresql/provision/main.tf
- terraform/cloudsql/postgresql/provision/outputs.tf
- terraform/cloudsql/postgresql/provision/provider.tf
- terraform/cloudsql/postgresql/provision/variables.tf
Co-authored-by: Felisia Martini <fmartini@pivotal.io>
> feat: enabling tls for postgres by default

- google-postgresql.yml
[#181806658](https://www.pivotaltracker.com/story/show/181806658)
> docs: amend public_ip description

- terraform/cloudsql/postgresql/provision/main.tf
> chore(PostgreSQL): use strong passwords for management accounts

- terraform/cloudsql/mysql/bind/outputs.tf
- terraform/cloudsql/postgresql/bind/main.tf
- terraform/cloudsql/postgresql/bind/outputs.tf
- terraform/cloudsql/postgresql/provision/main.tf
- terraform/cloudsql/postgresql/provision/versions.tf
> chore: format Terraform HCL

- terraform/cloudsql/postgresql/bind/outputs.tf
> build(PostgreSQL): TLS connections - fix build

- Makefile
- docs/configuration.md
- docs/draft-release-notes.md
- google-postgresql.yml
- integration-tests/postgres_test.go
- terraform/cloudsql/postgresql/provision/data.tf
- terraform/cloudsql/postgresql/provision/main.tf
- terraform/cloudsql/postgresql/provision/variables.tf
> feat: expose google sql service tiers

- providers/terraform-provider-csbpg/csbpg/resource_binding_user.go
- providers/terraform-provider-csbpg/resource_binding_user_test.go
[#181898458]
Co-authored-by: James Norman <normanja@vmware.com>
~~* [ ] Have you added Draft Release Notes in `docs/draft-release-notes.md`?~~
> chore: adding delete for the custom binding provider

- acceptance-tests/apps/stackdrivertraceapp/index.js
- acceptance-tests/apps/stackdrivertraceapp/package-lock.json
- acceptance-tests/apps/stackdrivertraceapp/package.json
There are many opinions on how to write good JavaScript.
StandardJS requires no configuration and provides consistent formatting and linting.
> chore: use "standard" formatting

- Makefile
- acceptance-tests/helpers/brokers/env.go
- acceptance-tests/postgresql_test.go
- acceptance-tests/withoutcredhub_test.go
- docs/draft-release-notes.md
- google-postgresql.yml
- scripts/push-broker.sh
[#181342507](https://www.pivotaltracker.com/story/show/181342507)
> feat(postgres): remove "beta" label prior to GA

- Makefile
- acceptance-tests/helpers/brokers/env.go
- google-postgresql.yml
- integration-tests/postgres_test.go
[#181805808](https://www.pivotaltracker.com/story/show/181805808)
> feat: tier property now free text field to allow custom dbs

- providers/terraform-provider-csbpg/csbpg/connection_factory.go
- providers/terraform-provider-csbpg/csbpg/data_owner_role.go
- providers/terraform-provider-csbpg/csbpg/resource_binding_user.go
- providers/terraform-provider-csbpg/resource_binding_user_test.go
- providers/terraform-provider-csbpg/testfixtures/ssl_postgres/init.sql
- providers/terraform-provider-csbpg/testfixtures/ssl_postgres/pgconf/pg_hba.conf
[#181898458]
Co-authored-by: Felisia Martini <fmartini@pivotal.io>
~~* [ ] Have you added Draft Release Notes in `docs/draft-release-notes.md`?~~
> chore: implementing unbind with role data reassignment

- docs/draft-release-notes.md
- terraform/cloudsql/postgresql/provision/main.tf
[#181900418]
Co-authored-by: Felisia Martini <fmartini@pivotal.io>
> fix: Improve password length for admin user

- integration-tests/mysql_test.go
> test: extend the test to more properties

- integration-tests/postgres_test.go
[#181404871](https://www.pivotaltracker.com/story/show/181404871)
> test: improve postgres catalog test

- integration-tests/mysql_test.go
[#181404871](https://www.pivotaltracker.com/story/show/181404871)
> test: prevent users update parameters

- integration-tests/postgres_test.go
> test: improve postgres integration tests

- integration-tests/mysql_test.go
- integration-tests/postgres_test.go
- integration-tests/redis_test.go
[#182362436](https://www.pivotaltracker.com/story/show/182362436)
> test: set initial Terraform state

- google-bigquery.yml
- google-dataproc.yml
- google-mysql.yml
- google-postgresql.yml
- google-spanner.yml
- google-stackdriver-trace.yml
- google-storage.yml
- integration-tests/bigquery_test.go
- integration-tests/dataproc_test.go
- integration-tests/mysql_test.go
- integration-tests/postgres_test.go
- integration-tests/spanner_test.go
- integration-tests/storage_test.go
- staticcheck.conf
> chore: Use text field in the region property

- google-postgresql.yml
- integration-tests/postgres_test.go
[#182299591](https://www.pivotaltracker.com/story/show/182299591)
> fix: incorrect field type to establish the backup location

- acceptance-tests/upgrade/update_and_upgrade_dataproc_test.go
- acceptance-tests/upgrade/update_and_upgrade_redis_test.go
- acceptance-tests/upgrade/update_and_upgrade_spanner_test.go
> test: Fix upgrade tests

- docs/draft-release-notes.md
- manifest.yml
> feat: Update TF version to v1.2.4

- acceptance-tests/helpers/brokers/update.go
[#182771270](https://www.pivotaltracker.com/story/show/182771270)
> test: speed up broker update

- README.md
[#182841592](https://www.pivotaltracker.com/story/show/182841592)
> fix: incorrect link to installation

- Makefile
- go.mod
- go.sum
- terraform-tests/README.md
- terraform-tests/helpers/resource_changes.go
- terraform-tests/helpers/terraform.go
- terraform-tests/mysql_test.go
- terraform-tests/terraform_tests_suite_test.go
[#183885635](https://www.pivotaltracker.com/story/show/183885635)
* ~[ ] Have you added Release Notes in the docs repositories?~
> test: Added terraform test frameworks

- google-mysql.yml
- integration-tests/mysql_test.go
- terraform-tests/mysql_test.go
- terraform/cloudsql/mysql/provision/main.tf
- terraform/cloudsql/mysql/provision/variables.tf
[#183885800](https://www.pivotaltracker.com/story/show/183885800)
> feat: enable deletion protection

- terraform/cloudsql/mysql/provision/main.tf
* ~[ ] Have you added Release Notes in the docs repositories?~
> fix: Corrected MySQL TF variable name

- terraform/cloudsql/mysql/provision/main.tf
[#183975670](https://www.pivotaltracker.com/story/show/183975670)
> feat: Match password policy with PostgreSQL

- google-mysql.yml
- integration-tests/mysql_test.go
- terraform-tests/mysql_test.go
- terraform-tests/terraform_tests_suite_test.go
- terraform/cloudsql/mysql/provision/data.tf
- terraform/cloudsql/mysql/provision/main.tf
- terraform/cloudsql/mysql/provision/variables.tf
[#183876959](https://www.pivotaltracker.com/story/show/183876959)
> feat: [MySQL] Enable backup configuration

- google-mysql.yml
- integration-tests/mysql_test.go
- terraform-tests/mysql_test.go
- terraform/cloudsql/mysql/provision/main.tf
- terraform/cloudsql/mysql/provision/variables.tf
[#183876947](https://www.pivotaltracker.com/story/show/183876947)
> feat: Enable public IP address

- google-mysql.yml
- integration-tests/mysql_test.go
- terraform/cloudsql/mysql/provision/data.tf
- terraform/cloudsql/mysql/provision/variables.tf
Reverts cloudfoundry/csb-brokerpak-gcp#586
> chore: revert commit remove authorized_network parameter

- Makefile
- docs/configuration.md
- google-mysql.yml
- integration-tests/mysql_test.go
- scripts/cf-test-broker.sh
- terraform/cloudsql/mysql/provision/data.tf
- terraform/cloudsql/mysql/provision/variables.tf
[#183975388](https://www.pivotaltracker.com/story/show/183975388)
~~* [ ] Have you added Release Notes in the docs repositories?~~
> chore: use authorized_network_id in internal tooling

- acceptance-tests/mysql_test.go
- acceptance-tests/postgresql_test.go
- google-mysql.yml
- google-postgresql.yml
- integration-tests/postgres_test.go
- terraform/cloudsql/mysql/bind/provider.tf
- terraform/cloudsql/mysql/bind/variables.tf
- terraform/cloudsql/mysql/provision/outputs.tf
- terraform/cloudsql/postgresql/bind/provider.tf
- terraform/cloudsql/postgresql/bind/variables.tf
- terraform/cloudsql/postgresql/provision/outputs.tf
[#184083158](https://www.pivotaltracker.com/story/show/184083158)
* ~[ ] Have you added Release Notes in the docs repositories?~
> chore: [GCP MySQL & PostgreSQL] Fix public IP binding creation

- google-storage.yml
- terraform/storage/provision/variables.tf
The parameter is not being used.
[#184053404](https://www.pivotaltracker.com/story/show/184053404)
> chore: Remove acl plan parameter

- acceptance-tests/apps/mysqlapp/internal/credentials/credentials.go
- google-mysql.yml
- terraform-tests/mysql_test.go
- terraform/cloudsql/mysql/bind/main.tf
- terraform/cloudsql/mysql/bind/outputs.tf
- terraform/cloudsql/mysql/bind/variables.tf
- terraform/cloudsql/mysql/provision/main.tf
- terraform/cloudsql/mysql/provision/outputs.tf
- terraform/cloudsql/postgresql/provision/variables.tf
[#181059904](https://www.pivotaltracker.com/story/show/181059904)
> feat: [mysql] enable TLS

- google-storage.yml
- terraform/storage/bind/outputs.tf
[#184053361](https://www.pivotaltracker.com/story/show/184053361)
> chore: binding result using snake case format

- Makefile
- acceptance-tests/helpers/brokers/create.go
- acceptance-tests/helpers/brokers/env.go
- acceptance-tests/mysql_test.go
- acceptance-tests/upgrade/update_and_upgrade_dataproc_test.go
- acceptance-tests/upgrade/update_and_upgrade_mysql_test.go
- acceptance-tests/upgrade/update_and_upgrade_postgresql_test.go
- acceptance-tests/upgrade/update_and_upgrade_redis_test.go
- acceptance-tests/upgrade/update_and_upgrade_spanner_test.go
- acceptance-tests/upgrade/update_and_upgrade_storage_test.go
- acceptance-tests/upgrade/upgrade_stackdrivertrace_test.go
- google-mysql.yml
- integration-tests/mysql_test.go
- scripts/push-broker.sh
[#184051243](https://www.pivotaltracker.com/story/show/184051243)
> feat: remove the built-in plans - MySQL

- google-mysql.yml
[#184012020](https://www.pivotaltracker.com/story/show/184012020)
> fix: execute example using default plan

- .gitignore
- acceptance-tests/apps/mysqlapp/Procfile
- acceptance-tests/mysql_test.go
- google-storage.yml
- integration-tests/storage_test.go
- terraform-tests/storage_test.go
[#184044557](https://www.pivotaltracker.com/story/show/184044557)
> feat: Multi-Regional storage class by default

- google-storage.yml
- integration-tests/storage_test.go
- terraform-tests/storage_test.go
[#184044557](https://www.pivotaltracker.com/story/show/184044557)
> chore: US as default region when multi-region is selected

- acceptance-tests/upgrade/update_and_upgrade_storage_test.go
[#184044692](https://www.pivotaltracker.com/story/show/184044692)
> fix: use a valid storage class to match with the default region

- acceptance-tests/upgrade/update_and_upgrade_storage_test.go
[#184044557](https://www.pivotaltracker.com/story/show/184044557)
> fix: acceptance tests using old default values

- google-storage.yml
- integration-tests/storage_test.go
- terraform-tests/storage_test.go
- terraform/storage/provision/main.tf
- terraform/storage/provision/variables.tf
[#184044702](https://www.pivotaltracker.com/story/show/184044702)
> feat: [storage-bucket] expose uniform_bucket_level_access

- google-storage.yml
- integration-tests/storage_test.go
[#184044836](https://www.pivotaltracker.com/story/show/184044836)
> chore: versioning false by default

- google-storage.yml
- integration-tests/storage_test.go
[#184044702](https://www.pivotaltracker.com/story/show/184044702)
> chore: uniform_bucket_level_access set false by default

- google-storage.yml
[#184044692](https://www.pivotaltracker.com/story/show/184044692)
> chore: improve dual-region configuration documentation

- acceptance-tests/apps/mysqlapp/internal/credentials/credentials.go
- acceptance-tests/upgrade/update_and_upgrade_mysql_test.go
[#184239496](https://www.pivotaltracker.com/story/show/184239496)
> chore: Adapt upgrade test to use old and new binding format

- google-storage.yml
- integration-tests/storage_test.go
- terraform-tests/storage_test.go
- terraform/storage/provision/main.tf
- terraform/storage/provision/variables.tf
[#184045227](https://www.pivotaltracker.com/story/show/184045227)
> feat: [Cloud Storage] expose encryption

- terraform-tests/storage_test.go
- terraform/storage/provision/main.tf
> fix: avoid recreation bucket using dual-region

- google-storage.yml
[#184053043](https://www.pivotaltracker.com/story/show/184053043)
> chore: improve autoclass feature documentation

- acceptance-tests/apps/mysqlapp/internal/app/app.go
- acceptance-tests/apps/mysqlapp/internal/app/ssl_cipher.go
- acceptance-tests/apps/mysqlapp/internal/credentials/credentials.go
- acceptance-tests/upgrade/update_and_upgrade_mysql_test.go
- google-mysql.yml
- manifest.yml
- terraform/cloudsql/mysql/bind/data.tf
- terraform/cloudsql/mysql/bind/main.tf
- terraform/cloudsql/mysql/bind/outputs.tf
- terraform/cloudsql/mysql/bind/provider.tf
- terraform/cloudsql/mysql/bind/variables.tf
- terraform/cloudsql/mysql/bind/versions.tf
- terraform/cloudsql/mysql/provision/versions.tf
[#180913283](https://www.pivotaltracker.com/story/show/180913283)
> feat: use the new MySQL Terraform Provider

- google-mysql.yml
- integration-tests/mysql_test.go
- terraform-tests/mysql_test.go
- terraform/cloudsql/mysql/provision/data.tf
- terraform/cloudsql/mysql/provision/main.tf
- terraform/cloudsql/mysql/provision/variables.tf
[#184303419](https://www.pivotaltracker.com/story/show/184303419)
> feat: [MySQL] Enable HA configuration

- integration-tests/bigquery_test.go
- integration-tests/dataproc_test.go
- integration-tests/mysql_test.go
- integration-tests/postgres_test.go
- integration-tests/redis_test.go
- integration-tests/spanner_test.go
- integration-tests/storage_test.go
Continuation of #600, adding checks of actual values
> test: improve matching in integration tests

- google-storage.yml
These updates clarify some points, and add editing that was done for the Tanzu docs.
[#184045402](https://www.pivotaltracker.com/story/show/184045402)
> docs: update some wording for retiontion policy

- .cfignore
> chore: make service image work when pushing the app

- acceptance-tests/apps/jdbctestapp/manifest-no-autotls.yml
- acceptance-tests/apps/jdbctestapp/manifest.yml
- acceptance-tests/errormessages_test.go
- acceptance-tests/helpers/apps/delete.go
- acceptance-tests/helpers/apps/push.go
- acceptance-tests/helpers/apps/restage.go
- acceptance-tests/helpers/apps/restart.go
- acceptance-tests/helpers/apps/start.go
- acceptance-tests/helpers/apps/testapps.go
- acceptance-tests/helpers/cf/start.go
- acceptance-tests/helpers/services/delete.go
- acceptance-tests/helpers/services/update.go
- acceptance-tests/helpers/services/upgrade.go
- acceptance-tests/mysql_test.go
- google-mysql.yml
- integration-tests/mysql_test.go
- integration-tests/redis_test.go
- terraform-tests/helpers/resource_changes.go
- terraform-tests/mysql_test.go
- terraform/cloudsql/mysql/bind/data.tf
- terraform/cloudsql/mysql/bind/main.tf
- terraform/cloudsql/mysql/bind/outputs.tf
- terraform/cloudsql/mysql/bind/provider.tf
- terraform/cloudsql/mysql/bind/variables.tf
- terraform/cloudsql/mysql/bind/versions.tf
- terraform/cloudsql/mysql/provision/outputs.tf
- terraform/cloudsql/mysql/provision/variables.tf
[#184278537](https://www.pivotaltracker.com/story/show/184278537)
> feat: [mysql] Allow disabling binding SSL

- acceptance-tests/helpers/brokers/env.go
- acceptance-tests/upgrade/update_and_upgrade_storage_test.go
[#184053110](https://www.pivotaltracker.com/story/show/184053110)
> test: add needed environment variables for Storage

- manifest.yml
[#184504690](https://www.pivotaltracker.com/story/show/184504690)
> feat: update to Terraform v1.3.9

- Makefile
Removed variables that are no longer needed or duplicated in .envrc
> chore: remove unnecessary variables from Makefile

- acceptance-tests/apps/mysqlapp/go.mod
- acceptance-tests/apps/mysqlapp/go.sum
- acceptance-tests/apps/mysqlapp/internal/credentials/binding.go
- acceptance-tests/apps/mysqlapp/internal/credentials/credentials.go
- acceptance-tests/apps/mysqlapp/internal/credentials/legacy_broker_binding.go
[#184048087](https://www.pivotaltracker.com/story/show/184048087)
> test: update MySQL app to work with legacy broker bindings

- acceptance-tests/apps/dataprocapp/go.mod
- acceptance-tests/apps/dataprocapp/go.sum
[#184505023](https://www.pivotaltracker.com/story/show/184505023)
> chore: update golang.org/x/net dependency

- acceptance-tests/cloudsql_pg_migration_test.go
- acceptance-tests/helpers/services/create.go
This test has not been automated until now, and it looks like the plan names have drifted apart.
[#184048087](https://www.pivotaltracker.com/story/show/184048087)
> test: fix PostgreSQL data migration tests

- acceptance-tests/apps/storageapp/internal/credentials/credentials.go
- acceptance-tests/helpers/gcloud/gcp.go
- acceptance-tests/storage_migration_test.go
[#184053109](https://www.pivotaltracker.com/story/show/184053109)
> test: [Cloud Storage] add migration test

- acceptance-tests/cloudsql_mysql_migration_test.go
- acceptance-tests/cloudsql_pg_migration_test.go
- acceptance-tests/helpers/brokers/env.go
- acceptance-tests/helpers/gsql/sql.go
- acceptance-tests/helpers/legacybindings/extract.go
[#184048087](https://www.pivotaltracker.com/story/show/184048087)
> test: legacy broker MySQL data migration

- google-mysql.yml
- google-storage.yml
> chore: add GCP MySQL && Storage example

- google-storage.yml
- integration-tests/storage_test.go
[#184557377](https://www.pivotaltracker.com/story/show/184557377)
> chore: use enum storage_class & public_access_prev

- google-storage.yml
- integration-tests/storage_test.go
[#184053107](https://www.pivotaltracker.com/story/show/184053107)
> feat: set Cloud Storage as GA

- acceptance-tests/apps/mysqlapp/internal/credentials/credentials.go
- acceptance-tests/upgrade/update_and_upgrade_mysql_test.go
[#184016070](https://www.pivotaltracker.com/story/show/184016070)
> test: MySQL upgrade test updated after release

- terraform-tests/mysql_test.go
> test: new project property in database instance - TF tests

- google-postgresql.yml
- integration-tests/postgres_test.go
[#186050261](https://www.pivotaltracker.com/story/show/186050261)
> feat: remove enum for postgres_version

- google-postgresql.yml
- integration-tests/postgres_test.go
- terraform-tests/postgres_test.go
- terraform/cloudsql/postgresql/provision/data.tf
- terraform/cloudsql/postgresql/provision/main.tf
- terraform/cloudsql/postgresql/provision/variables.tf
[#182126463](https://www.pivotaltracker.com/story/show/182126463)
> feat: [Postgres] expose high availability

- manifest.yml
[#184671350](https://www.pivotaltracker.com/story/show/184671350)
~~* [ ] Have you added Release Notes in the docs repositories?~~
> chore: upgrade terraform to latest open source terraform

- acceptance-tests/apps/dataprocapp/go.mod
- acceptance-tests/apps/mysqlapp/go.mod
- acceptance-tests/apps/postgresqlapp/go.mod
- acceptance-tests/apps/redisapp/go.mod
- acceptance-tests/apps/spannerapp/go.mod
- acceptance-tests/apps/storageapp/go.mod
- go.mod
> chore: specify go1.22.0 in gomod 2

- .github/labeler.yml
- .github/release.yml
> chore: Ignore any test dependencies on release notes

- .github/dependabot.yml
- .github/labeler.yml
- .github/release.yml
> chore: Rely on dependabot to label its PRs

- google-storage.yml
- integration-tests/storage_test.go
- terraform-tests/README.md
[#187200917](https://www.pivotaltracker.com/story/show/187200917)
> docs: update documentation to not mention terraform anymore

- .github/dependabot.yml
[#187726190](https://www.pivotaltracker.com/story/show/187726190)
> chore: update pubsub app dependencies

- google-pubsub.yml
- terraform/pubsub/bind/main.tf
> feat: pubsub bindings #187726208

- manifest.yml
> feat: Update tofu to latest 1.7.2

- docs/README.md
- google-pubsub.yml
- integration-tests/pubsub_test.go
- terraform-tests/pubsub_test.go
- terraform/pubsub/provision/main.tf
- terraform/pubsub/provision/variables.tf
[#187726204](https://www.pivotaltracker.com/story/show/187726204)
> feat: Implement additional simple properties for topic and subscription

- google-dataproc.yml
- google-spanner.yml
- terraform/dataproc/bind/variables.tf
- terraform/spanner/bind/variables.tf
[#187846035](https://www.pivotaltracker.com/story/show/187846035)
> chore: Add missing variable declaration

- manifest.yml
> feat: Update tofu to latest v1.8.1

- google-mysql.yml
- google-postgresql.yml
- google-storage.yml
> chore: remove examples-test

- acceptance-tests/apps/springstorageapp/pom.xml
> chore: include metadata to enhance Dependabot information

- .github/dependabot.yml
> chore: update Java Application dependencies

- .github/dependabot.yml
> chore: reject release candidates for Maven packages

- .github/dependabot.yml
> chore: ignore spring boot framework

- acceptance-tests/apps/springstorageapp/README.md
- acceptance-tests/apps/springstorageapp/pom.xml
Incompatibility between dependencies
Dependabot has been configured to ignore the Spring Boot dependency
> test: storage java app dependencies

- acceptance-tests/helpers/services/delete.go
- acceptance-tests/upgrade/update_and_upgrade_mysql_test.go
- acceptance-tests/upgrade/update_and_upgrade_postgresql_test.go
- acceptance-tests/upgrade/update_and_upgrade_storage_test.go
- acceptance-tests/withoutcredhub_test.go
This reverts commit b959e104d9ddf9f650bb8f00fec64c8e8c1a640f.
> chore:  Revert - "chore: Fixes broker 'failed to allocate errors' (#1418)"

- google-mysql.yml
- google-postgresql.yml
- google-storage.yml
- integration-tests/integration_tests_suite_test.go
Previous docs links results in an unhelpful redirect, while this new link goes to a more helpful place.
> chore: update docs links
